title: Precogs
description: "Архив предсказаний о будущем. Predictions archive."
url: "https://luvor.github.io"
baseurl: "/precogs"
author: luvor
future: true

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - scope:
      path: "_posts/ru"
    values:
      lang: ru
      layout: prediction
      permalink: /ru/:year/:month/:day/:slug/
  - scope:
      path: "_posts/en"
    values:
      lang: en
      layout: prediction
      permalink: /en/:year/:month/:day/:slug/

include:
  - manifest.webmanifest
  - sw.js

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed
